# Use root/example as user/password credentials
version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./mysql/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    expose:
      - '3306'
    ports:
      - '3306:3306'
    networks:
      - app-network

  web:
    container_name: web
    build:
      context: .
    depends_on:
      - db
    # extra_hosts:
    #   - "somehost:0.0.0.0"
    ports: 
      - '8080:8080'
    networks:
     - app-network
    command: ["npm", "start"]
  
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - '8081:8080'
    depends_on:
      - db
    networks:
     - app-network

networks:
  app-network:
    driver: bridge
